#!/bin/bash
fn=~/jolts/$(date +%Y-%m-%d-%H-%M-%S).md
echo "# " >> "$fn"
rotated=$(xrandr | grep "1200 x 1920")
if [ -z "$rotated" ]; then
  st -i -g =80x20+1050+400 -e micro +1:3 "$fn"
else 
  st -i -g =80x20+300+500 -e micro +1:3 "$fn"
fi
content=$(cat "$fn")
if [ "$content" = "# " ]; then
  rm "$fn"
fi

