hook global WinCreate .* %{addhl number_lines}
colorscheme dark
map global normal = <a-i>
map global normal 0 gh
hook global WinSetOption filetype=cpp %{
  clang-enable-autocomplete
}

map global normal ` 'f{m<a-;>;'
map global normal <a-`> 'ghF{ML' 

map global normal <tab> '<a-;>'

map global normal <backspace> 'eval ga'
map global normal <f1> 'eval :b '
map global insert <tab> '    '

map global normal <f12> 'eval :cmake<ret>' 
map global normal <c-p> 'eval :e '


decl -hidden regex curword
face CurWord default,rgb:300010

hook global WinCreate .* %{
    addhl show_matching
    addhl dynregex '%reg{/}' 0:+u

    # Highlight the word under the cursor
    addhl dynregex '%opt{curword}' 0:CurWord
}

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>^\w+$<ret>
        set buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set buffer curword ''
    } }
}



# 【WIP】 Auto close matching block on insertion
hook global InsertChar '"' %{ auto_insert_char '"' }

#def -hidden -params 1 auto_insert_char %{
def -params 1 -docstring "test"  auto_insert_char %{
  eval -no-hooks %{
    try %{
      exec -draft %{ \; H <a-k> %arg{1} %arg{1} <ret> }
      exec '<del>'
    } \
    catch %{
      try %{
        exec -draft %{ \; h h <a-K> [ \w %arg{1} ] <ret> l <a-k> \W <ret> }
        exec %{ i %arg{1} <left> }
      }
    }
  }
}

def -params .. cc  -docstring "Create new c++ source and header files." %{
    %sh{
         echo "#include \"$@.hh\"" >> "$@".cc
         printf %s\\n "
             eval %{
             new
             edit "$@".cc
             write
             edit "$@".hh
             write
             buffer $kak_bufname
         }"
     }
}


def -params .. cmake -docstring "CMake utility wrapper" %{ %sh{
     while [ ! -f "CMakeLists.txt" ]; do cd ..; done
     output=$(mktemp -d -t kak-cmake.XXXXXXXX)/fifo
     output2=$(mktemp -d -t kak-cmake.XXXXXXXX)/fifo2
     mkfifo ${output}
     mkfifo ${output2}
     #( eval ${kak_opt_cmakecmd} "$@" > ${output} 2>&1 ) > /dev/null 2>&1 < /dev/null &
     builddir=$(mktemp -d -t kak-cmake.XXXXXXXX)
     mypwd=$(pwd)
     ( eval cd ${builddir} && cmake ${mypwd} "$@" > ${output} 2>&1 ; make -j 4 > ${output2} 2>&1 ) > /dev/null 2>&1 < /dev/null &
     printf %s\\n "eval -try-client '$kak_opt_toolsclient' %{
               edit! -fifo ${output} -scroll *cmake*
               set buffer filetype cmake
               hook -group fifo buffer BufCloseFifo .* %{
                   nop %sh{ rm -r $(dirname ${output}) }
                   rmhooks buffer fifo
               }
               edit! -fifo ${output2} -scroll *make*
               set buffer filetype make
               hook -group fifo buffer BufCloseFifo .* %{
                   nop %sh{ rm -r $(dirname ${output2}) }
                   rmhooks buffer fifo
                   buffer *cmake*
		   eval make-next
               }
           }"
} 
}

hook global WinSetOption filetype=cpp %{ set window formatcmd 'clang-format' }
hook global WinSetOption filetype=h %{ set window formatcmd 'clang-format' }
hook global WinSetOption filetype=(?!cpp).* %{ }
hook global BufWritePre .*(cpp) %{ format }

def clean_whitespaces %{
  eval -draft -itersel %{
    try %{ exec -draft -itersel s <ret>d          } catch %{ echo '' }
    try %{ exec -draft -itersel s^\h+|\h+$<ret>d  } catch %{ echo '' }
    try %{ exec -draft -itersel s\h+<ret>c<space> } catch %{ echo '' }
  }
}
